# If you want to rebuild all images, set this to --no-cache from the cli
DOCKER_ARGS?=

# You need to specify a particular target
#--------------------------------------------------------------------------
.PHONY: cpp_course
cpp_course:
	docker build ${DOCKER_ARGS} -t cpp_course cpp_course
